version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend_app
    depends_on:
      - db
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/nestjs_db"
    ports:
      - "3000:3000"
    command: npm run start:dev

volumes:
  postgres_data:
