version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: backend_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/nestjs_db"
    ports:
      - "3000:3000"

volumes:
  postgres_data: